export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESSFUL = 'LOGOUT_SUCCESSFUL';
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS';
export const INIT_COMPLETED = 'INIT_COMPLETED';
export const LOADING_FAILED = 'LOADING_FAILED';
