// flow-typed signature: 4190873a03b0c8bf7a38015c50c1f335
// flow-typed version: <<STUB>>/babel-plugin-transform-react-jsx-source_v^6.22.0/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-react-jsx-source'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-react-jsx-source' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-transform-react-jsx-source/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-transform-react-jsx-source/lib/index' {
  declare module.exports: $Exports<'babel-plugin-transform-react-jsx-source/lib'>;
}
declare module 'babel-plugin-transform-react-jsx-source/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-jsx-source/lib'>;
}
