// flow-typed signature: f98f8f10e2dacda9d7ba521d49c58cf3
// flow-typed version: <<STUB>>/expo-font_v^6.0.1/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'expo-font'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'expo-font' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'expo-font/build/ExpoFontLoader' {
  declare module.exports: any;
}

declare module 'expo-font/build/ExpoFontLoader.web' {
  declare module.exports: any;
}

declare module 'expo-font/build/Font' {
  declare module.exports: any;
}

// Filename aliases
declare module 'expo-font/build/ExpoFontLoader.js' {
  declare module.exports: $Exports<'expo-font/build/ExpoFontLoader'>;
}
declare module 'expo-font/build/ExpoFontLoader.web.js' {
  declare module.exports: $Exports<'expo-font/build/ExpoFontLoader.web'>;
}
declare module 'expo-font/build/Font.js' {
  declare module.exports: $Exports<'expo-font/build/Font'>;
}
