// flow-typed signature: 41146ad2e80d51fe4a7f1806159bdbeb
// flow-typed version: <<STUB>>/expo_v^34.0.3/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'expo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'expo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'expo/AppEntry' {
  declare module.exports: any;
}

declare module 'expo/bin/cli' {
  declare module.exports: any;
}

declare module 'expo/build/apisAreAvailable' {
  declare module.exports: any;
}

declare module 'expo/build/AR' {
  declare module.exports: any;
}

declare module 'expo/build/AuthSession' {
  declare module.exports: any;
}

declare module 'expo/build/Branch' {
  declare module.exports: any;
}

declare module 'expo/build/Branch.web' {
  declare module.exports: any;
}

declare module 'expo/build/DangerZone' {
  declare module.exports: any;
}

declare module 'expo/build/DangerZone.web' {
  declare module.exports: any;
}

declare module 'expo/build/deprecatedModule' {
  declare module.exports: any;
}

declare module 'expo/build/environment/logging.fx' {
  declare module.exports: any;
}

declare module 'expo/build/environment/muteWarnings.fx' {
  declare module.exports: any;
}

declare module 'expo/build/environment/validate.fx' {
  declare module.exports: any;
}

declare module 'expo/build/environment/validatorState' {
  declare module.exports: any;
}

declare module 'expo/build/ErrorRecovery/ErrorRecovery' {
  declare module.exports: any;
}

declare module 'expo/build/ErrorRecovery/ExponentErrorRecovery' {
  declare module.exports: any;
}

declare module 'expo/build/ErrorRecovery/ExponentErrorRecovery.web' {
  declare module.exports: any;
}

declare module 'expo/build/Expo.fx' {
  declare module.exports: any;
}

declare module 'expo/build/Expo.fx.web' {
  declare module.exports: any;
}

declare module 'expo/build/Expo' {
  declare module.exports: any;
}

declare module 'expo/build/ExpoLazy' {
  declare module.exports: any;
}

declare module 'expo/build/globals' {
  declare module.exports: any;
}

declare module 'expo/build/globals.web' {
  declare module.exports: any;
}

declare module 'expo/build/launch/AppLoading' {
  declare module.exports: any;
}

declare module 'expo/build/launch/AppLoadingNativeWrapper' {
  declare module.exports: any;
}

declare module 'expo/build/launch/registerRootComponent' {
  declare module.exports: any;
}

declare module 'expo/build/launch/registerRootComponent.web' {
  declare module.exports: any;
}

declare module 'expo/build/launch/RootErrorBoundary' {
  declare module.exports: any;
}

declare module 'expo/build/launch/RootErrorBoundary.web' {
  declare module.exports: any;
}

declare module 'expo/build/launch/SplashScreen' {
  declare module.exports: any;
}

declare module 'expo/build/launch/withExpoRoot' {
  declare module.exports: any;
}

declare module 'expo/build/launch/withExpoRoot.types' {
  declare module.exports: any;
}

declare module 'expo/build/launch/withExpoRoot.web' {
  declare module.exports: any;
}

declare module 'expo/build/Linking/Linking' {
  declare module.exports: any;
}

declare module 'expo/build/Linking/Linking.types' {
  declare module.exports: any;
}

declare module 'expo/build/Linking/LinkingModule' {
  declare module.exports: any;
}

declare module 'expo/build/Linking/LinkingModule.web' {
  declare module.exports: any;
}

declare module 'expo/build/logs/format/ReactNodeFormatter' {
  declare module.exports: any;
}

declare module 'expo/build/logs/Logs' {
  declare module.exports: any;
}

declare module 'expo/build/logs/Logs.web' {
  declare module.exports: any;
}

declare module 'expo/build/logs/LogSerialization' {
  declare module.exports: any;
}

declare module 'expo/build/logs/RemoteConsole' {
  declare module.exports: any;
}

declare module 'expo/build/logs/RemoteLogging' {
  declare module.exports: any;
}

declare module 'expo/build/Notifications/ExponentNotifications' {
  declare module.exports: any;
}

declare module 'expo/build/Notifications/ExponentNotifications.web' {
  declare module.exports: any;
}

declare module 'expo/build/Notifications/Notifications' {
  declare module.exports: any;
}

declare module 'expo/build/Notifications/Notifications.types' {
  declare module.exports: any;
}

declare module 'expo/build/Payments' {
  declare module.exports: any;
}

declare module 'expo/build/removed' {
  declare module.exports: any;
}

declare module 'expo/build/removed.web' {
  declare module.exports: any;
}

declare module 'expo/build/removedModule' {
  declare module.exports: any;
}

declare module 'expo/build/ScreenOrientation/ExpoScreenOrientation' {
  declare module.exports: any;
}

declare module 'expo/build/ScreenOrientation/ExpoScreenOrientation.web' {
  declare module.exports: any;
}

declare module 'expo/build/ScreenOrientation/ScreenOrientation' {
  declare module.exports: any;
}

declare module 'expo/build/ScreenOrientation/ScreenOrientation.types' {
  declare module.exports: any;
}

declare module 'expo/build/StoreReview/ExponentStoreReview' {
  declare module.exports: any;
}

declare module 'expo/build/StoreReview/ExponentStoreReview.web' {
  declare module.exports: any;
}

declare module 'expo/build/StoreReview/StoreReview' {
  declare module.exports: any;
}

declare module 'expo/build/takeSnapshotAsync/captureRef' {
  declare module.exports: any;
}

declare module 'expo/build/takeSnapshotAsync/captureRef.web' {
  declare module.exports: any;
}

declare module 'expo/build/takeSnapshotAsync/Creator.web' {
  declare module.exports: any;
}

declare module 'expo/build/takeSnapshotAsync/Fonts.web' {
  declare module.exports: any;
}

declare module 'expo/build/takeSnapshotAsync/Images.web' {
  declare module.exports: any;
}

declare module 'expo/build/takeSnapshotAsync/ProcessSources.web' {
  declare module.exports: any;
}

declare module 'expo/build/takeSnapshotAsync/Utils.web' {
  declare module.exports: any;
}

declare module 'expo/build/timer/polyfillNextTick' {
  declare module.exports: any;
}

declare module 'expo/build/Updates/ExponentUpdates' {
  declare module.exports: any;
}

declare module 'expo/build/Updates/ExponentUpdates.web' {
  declare module.exports: any;
}

declare module 'expo/build/Updates/Updates' {
  declare module.exports: any;
}

declare module 'expo/tools/hashAssetFiles' {
  declare module.exports: any;
}

declare module 'expo/tools/LogReporter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'expo/AppEntry.js' {
  declare module.exports: $Exports<'expo/AppEntry'>;
}
declare module 'expo/bin/cli.js' {
  declare module.exports: $Exports<'expo/bin/cli'>;
}
declare module 'expo/build/apisAreAvailable.js' {
  declare module.exports: $Exports<'expo/build/apisAreAvailable'>;
}
declare module 'expo/build/AR.js' {
  declare module.exports: $Exports<'expo/build/AR'>;
}
declare module 'expo/build/AuthSession.js' {
  declare module.exports: $Exports<'expo/build/AuthSession'>;
}
declare module 'expo/build/Branch.js' {
  declare module.exports: $Exports<'expo/build/Branch'>;
}
declare module 'expo/build/Branch.web.js' {
  declare module.exports: $Exports<'expo/build/Branch.web'>;
}
declare module 'expo/build/DangerZone.js' {
  declare module.exports: $Exports<'expo/build/DangerZone'>;
}
declare module 'expo/build/DangerZone.web.js' {
  declare module.exports: $Exports<'expo/build/DangerZone.web'>;
}
declare module 'expo/build/deprecatedModule.js' {
  declare module.exports: $Exports<'expo/build/deprecatedModule'>;
}
declare module 'expo/build/environment/logging.fx.js' {
  declare module.exports: $Exports<'expo/build/environment/logging.fx'>;
}
declare module 'expo/build/environment/muteWarnings.fx.js' {
  declare module.exports: $Exports<'expo/build/environment/muteWarnings.fx'>;
}
declare module 'expo/build/environment/validate.fx.js' {
  declare module.exports: $Exports<'expo/build/environment/validate.fx'>;
}
declare module 'expo/build/environment/validatorState.js' {
  declare module.exports: $Exports<'expo/build/environment/validatorState'>;
}
declare module 'expo/build/ErrorRecovery/ErrorRecovery.js' {
  declare module.exports: $Exports<'expo/build/ErrorRecovery/ErrorRecovery'>;
}
declare module 'expo/build/ErrorRecovery/ExponentErrorRecovery.js' {
  declare module.exports: $Exports<'expo/build/ErrorRecovery/ExponentErrorRecovery'>;
}
declare module 'expo/build/ErrorRecovery/ExponentErrorRecovery.web.js' {
  declare module.exports: $Exports<'expo/build/ErrorRecovery/ExponentErrorRecovery.web'>;
}
declare module 'expo/build/Expo.fx.js' {
  declare module.exports: $Exports<'expo/build/Expo.fx'>;
}
declare module 'expo/build/Expo.fx.web.js' {
  declare module.exports: $Exports<'expo/build/Expo.fx.web'>;
}
declare module 'expo/build/Expo.js' {
  declare module.exports: $Exports<'expo/build/Expo'>;
}
declare module 'expo/build/ExpoLazy.js' {
  declare module.exports: $Exports<'expo/build/ExpoLazy'>;
}
declare module 'expo/build/globals.js' {
  declare module.exports: $Exports<'expo/build/globals'>;
}
declare module 'expo/build/globals.web.js' {
  declare module.exports: $Exports<'expo/build/globals.web'>;
}
declare module 'expo/build/launch/AppLoading.js' {
  declare module.exports: $Exports<'expo/build/launch/AppLoading'>;
}
declare module 'expo/build/launch/AppLoadingNativeWrapper.js' {
  declare module.exports: $Exports<'expo/build/launch/AppLoadingNativeWrapper'>;
}
declare module 'expo/build/launch/registerRootComponent.js' {
  declare module.exports: $Exports<'expo/build/launch/registerRootComponent'>;
}
declare module 'expo/build/launch/registerRootComponent.web.js' {
  declare module.exports: $Exports<'expo/build/launch/registerRootComponent.web'>;
}
declare module 'expo/build/launch/RootErrorBoundary.js' {
  declare module.exports: $Exports<'expo/build/launch/RootErrorBoundary'>;
}
declare module 'expo/build/launch/RootErrorBoundary.web.js' {
  declare module.exports: $Exports<'expo/build/launch/RootErrorBoundary.web'>;
}
declare module 'expo/build/launch/SplashScreen.js' {
  declare module.exports: $Exports<'expo/build/launch/SplashScreen'>;
}
declare module 'expo/build/launch/withExpoRoot.js' {
  declare module.exports: $Exports<'expo/build/launch/withExpoRoot'>;
}
declare module 'expo/build/launch/withExpoRoot.types.js' {
  declare module.exports: $Exports<'expo/build/launch/withExpoRoot.types'>;
}
declare module 'expo/build/launch/withExpoRoot.web.js' {
  declare module.exports: $Exports<'expo/build/launch/withExpoRoot.web'>;
}
declare module 'expo/build/Linking/Linking.js' {
  declare module.exports: $Exports<'expo/build/Linking/Linking'>;
}
declare module 'expo/build/Linking/Linking.types.js' {
  declare module.exports: $Exports<'expo/build/Linking/Linking.types'>;
}
declare module 'expo/build/Linking/LinkingModule.js' {
  declare module.exports: $Exports<'expo/build/Linking/LinkingModule'>;
}
declare module 'expo/build/Linking/LinkingModule.web.js' {
  declare module.exports: $Exports<'expo/build/Linking/LinkingModule.web'>;
}
declare module 'expo/build/logs/format/ReactNodeFormatter.js' {
  declare module.exports: $Exports<'expo/build/logs/format/ReactNodeFormatter'>;
}
declare module 'expo/build/logs/Logs.js' {
  declare module.exports: $Exports<'expo/build/logs/Logs'>;
}
declare module 'expo/build/logs/Logs.web.js' {
  declare module.exports: $Exports<'expo/build/logs/Logs.web'>;
}
declare module 'expo/build/logs/LogSerialization.js' {
  declare module.exports: $Exports<'expo/build/logs/LogSerialization'>;
}
declare module 'expo/build/logs/RemoteConsole.js' {
  declare module.exports: $Exports<'expo/build/logs/RemoteConsole'>;
}
declare module 'expo/build/logs/RemoteLogging.js' {
  declare module.exports: $Exports<'expo/build/logs/RemoteLogging'>;
}
declare module 'expo/build/Notifications/ExponentNotifications.js' {
  declare module.exports: $Exports<'expo/build/Notifications/ExponentNotifications'>;
}
declare module 'expo/build/Notifications/ExponentNotifications.web.js' {
  declare module.exports: $Exports<'expo/build/Notifications/ExponentNotifications.web'>;
}
declare module 'expo/build/Notifications/Notifications.js' {
  declare module.exports: $Exports<'expo/build/Notifications/Notifications'>;
}
declare module 'expo/build/Notifications/Notifications.types.js' {
  declare module.exports: $Exports<'expo/build/Notifications/Notifications.types'>;
}
declare module 'expo/build/Payments.js' {
  declare module.exports: $Exports<'expo/build/Payments'>;
}
declare module 'expo/build/removed.js' {
  declare module.exports: $Exports<'expo/build/removed'>;
}
declare module 'expo/build/removed.web.js' {
  declare module.exports: $Exports<'expo/build/removed.web'>;
}
declare module 'expo/build/removedModule.js' {
  declare module.exports: $Exports<'expo/build/removedModule'>;
}
declare module 'expo/build/ScreenOrientation/ExpoScreenOrientation.js' {
  declare module.exports: $Exports<'expo/build/ScreenOrientation/ExpoScreenOrientation'>;
}
declare module 'expo/build/ScreenOrientation/ExpoScreenOrientation.web.js' {
  declare module.exports: $Exports<'expo/build/ScreenOrientation/ExpoScreenOrientation.web'>;
}
declare module 'expo/build/ScreenOrientation/ScreenOrientation.js' {
  declare module.exports: $Exports<'expo/build/ScreenOrientation/ScreenOrientation'>;
}
declare module 'expo/build/ScreenOrientation/ScreenOrientation.types.js' {
  declare module.exports: $Exports<'expo/build/ScreenOrientation/ScreenOrientation.types'>;
}
declare module 'expo/build/StoreReview/ExponentStoreReview.js' {
  declare module.exports: $Exports<'expo/build/StoreReview/ExponentStoreReview'>;
}
declare module 'expo/build/StoreReview/ExponentStoreReview.web.js' {
  declare module.exports: $Exports<'expo/build/StoreReview/ExponentStoreReview.web'>;
}
declare module 'expo/build/StoreReview/StoreReview.js' {
  declare module.exports: $Exports<'expo/build/StoreReview/StoreReview'>;
}
declare module 'expo/build/takeSnapshotAsync/captureRef.js' {
  declare module.exports: $Exports<'expo/build/takeSnapshotAsync/captureRef'>;
}
declare module 'expo/build/takeSnapshotAsync/captureRef.web.js' {
  declare module.exports: $Exports<'expo/build/takeSnapshotAsync/captureRef.web'>;
}
declare module 'expo/build/takeSnapshotAsync/Creator.web.js' {
  declare module.exports: $Exports<'expo/build/takeSnapshotAsync/Creator.web'>;
}
declare module 'expo/build/takeSnapshotAsync/Fonts.web.js' {
  declare module.exports: $Exports<'expo/build/takeSnapshotAsync/Fonts.web'>;
}
declare module 'expo/build/takeSnapshotAsync/Images.web.js' {
  declare module.exports: $Exports<'expo/build/takeSnapshotAsync/Images.web'>;
}
declare module 'expo/build/takeSnapshotAsync/ProcessSources.web.js' {
  declare module.exports: $Exports<'expo/build/takeSnapshotAsync/ProcessSources.web'>;
}
declare module 'expo/build/takeSnapshotAsync/Utils.web.js' {
  declare module.exports: $Exports<'expo/build/takeSnapshotAsync/Utils.web'>;
}
declare module 'expo/build/timer/polyfillNextTick.js' {
  declare module.exports: $Exports<'expo/build/timer/polyfillNextTick'>;
}
declare module 'expo/build/Updates/ExponentUpdates.js' {
  declare module.exports: $Exports<'expo/build/Updates/ExponentUpdates'>;
}
declare module 'expo/build/Updates/ExponentUpdates.web.js' {
  declare module.exports: $Exports<'expo/build/Updates/ExponentUpdates.web'>;
}
declare module 'expo/build/Updates/Updates.js' {
  declare module.exports: $Exports<'expo/build/Updates/Updates'>;
}
declare module 'expo/tools/hashAssetFiles.js' {
  declare module.exports: $Exports<'expo/tools/hashAssetFiles'>;
}
declare module 'expo/tools/LogReporter.js' {
  declare module.exports: $Exports<'expo/tools/LogReporter'>;
}
