// flow-typed signature: cc57c5646a6ebcbee2acb8f0cd8277b3
// flow-typed version: <<STUB>>/firebase-functions_v^2.2.0/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'firebase-functions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'firebase-functions' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'firebase-functions/lib/apps' {
  declare module.exports: any;
}

declare module 'firebase-functions/lib/cloud-functions' {
  declare module.exports: any;
}

declare module 'firebase-functions/lib/config' {
  declare module.exports: any;
}

declare module 'firebase-functions/lib/encoder' {
  declare module.exports: any;
}

declare module 'firebase-functions/lib/function-builder' {
  declare module.exports: any;
}

declare module 'firebase-functions/lib/handler-builder' {
  declare module.exports: any;
}

declare module 'firebase-functions/lib' {
  declare module.exports: any;
}

declare module 'firebase-functions/lib/providers/analytics' {
  declare module.exports: any;
}

declare module 'firebase-functions/lib/providers/auth' {
  declare module.exports: any;
}

declare module 'firebase-functions/lib/providers/crashlytics' {
  declare module.exports: any;
}

declare module 'firebase-functions/lib/providers/database' {
  declare module.exports: any;
}

declare module 'firebase-functions/lib/providers/firestore' {
  declare module.exports: any;
}

declare module 'firebase-functions/lib/providers/https' {
  declare module.exports: any;
}

declare module 'firebase-functions/lib/providers/pubsub' {
  declare module.exports: any;
}

declare module 'firebase-functions/lib/providers/remoteConfig' {
  declare module.exports: any;
}

declare module 'firebase-functions/lib/providers/storage' {
  declare module.exports: any;
}

declare module 'firebase-functions/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'firebase-functions/lib/apps.js' {
  declare module.exports: $Exports<'firebase-functions/lib/apps'>;
}
declare module 'firebase-functions/lib/cloud-functions.js' {
  declare module.exports: $Exports<'firebase-functions/lib/cloud-functions'>;
}
declare module 'firebase-functions/lib/config.js' {
  declare module.exports: $Exports<'firebase-functions/lib/config'>;
}
declare module 'firebase-functions/lib/encoder.js' {
  declare module.exports: $Exports<'firebase-functions/lib/encoder'>;
}
declare module 'firebase-functions/lib/function-builder.js' {
  declare module.exports: $Exports<'firebase-functions/lib/function-builder'>;
}
declare module 'firebase-functions/lib/handler-builder.js' {
  declare module.exports: $Exports<'firebase-functions/lib/handler-builder'>;
}
declare module 'firebase-functions/lib/index' {
  declare module.exports: $Exports<'firebase-functions/lib'>;
}
declare module 'firebase-functions/lib/index.js' {
  declare module.exports: $Exports<'firebase-functions/lib'>;
}
declare module 'firebase-functions/lib/providers/analytics.js' {
  declare module.exports: $Exports<'firebase-functions/lib/providers/analytics'>;
}
declare module 'firebase-functions/lib/providers/auth.js' {
  declare module.exports: $Exports<'firebase-functions/lib/providers/auth'>;
}
declare module 'firebase-functions/lib/providers/crashlytics.js' {
  declare module.exports: $Exports<'firebase-functions/lib/providers/crashlytics'>;
}
declare module 'firebase-functions/lib/providers/database.js' {
  declare module.exports: $Exports<'firebase-functions/lib/providers/database'>;
}
declare module 'firebase-functions/lib/providers/firestore.js' {
  declare module.exports: $Exports<'firebase-functions/lib/providers/firestore'>;
}
declare module 'firebase-functions/lib/providers/https.js' {
  declare module.exports: $Exports<'firebase-functions/lib/providers/https'>;
}
declare module 'firebase-functions/lib/providers/pubsub.js' {
  declare module.exports: $Exports<'firebase-functions/lib/providers/pubsub'>;
}
declare module 'firebase-functions/lib/providers/remoteConfig.js' {
  declare module.exports: $Exports<'firebase-functions/lib/providers/remoteConfig'>;
}
declare module 'firebase-functions/lib/providers/storage.js' {
  declare module.exports: $Exports<'firebase-functions/lib/providers/storage'>;
}
declare module 'firebase-functions/lib/utils.js' {
  declare module.exports: $Exports<'firebase-functions/lib/utils'>;
}
