// flow-typed signature: b146285e7c776dfe7cb37802caf64b14
// flow-typed version: <<STUB>>/node-stream-zip_v^1.8.0/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-stream-zip'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-stream-zip' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-stream-zip/node_stream_zip' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-stream-zip/node_stream_zip.js' {
  declare module.exports: $Exports<'node-stream-zip/node_stream_zip'>;
}
