// flow-typed signature: 7c623005e716c91331f56af99c0fc13e
// flow-typed version: <<STUB>>/react-native-modal-datetime-picker_v^7.5.0/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-modal-datetime-picker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-modal-datetime-picker' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-modal-datetime-picker/src/CustomDatePickerAndroid' {
  declare module.exports: any;
}

declare module 'react-native-modal-datetime-picker/src/CustomDatePickerIOS' {
  declare module.exports: any;
}

declare module 'react-native-modal-datetime-picker/src' {
  declare module.exports: any;
}

declare module 'react-native-modal-datetime-picker/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-modal-datetime-picker/src/CustomDatePickerAndroid.js' {
  declare module.exports: $Exports<'react-native-modal-datetime-picker/src/CustomDatePickerAndroid'>;
}
declare module 'react-native-modal-datetime-picker/src/CustomDatePickerIOS.js' {
  declare module.exports: $Exports<'react-native-modal-datetime-picker/src/CustomDatePickerIOS'>;
}
declare module 'react-native-modal-datetime-picker/src/index' {
  declare module.exports: $Exports<'react-native-modal-datetime-picker/src'>;
}
declare module 'react-native-modal-datetime-picker/src/index.js' {
  declare module.exports: $Exports<'react-native-modal-datetime-picker/src'>;
}
declare module 'react-native-modal-datetime-picker/src/utils.js' {
  declare module.exports: $Exports<'react-native-modal-datetime-picker/src/utils'>;
}
