// flow-typed signature: bf691f00d2c73d5b241102665a3d1299
// flow-typed version: <<STUB>>/react-native-version_v^3.2.0/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-version'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-version' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-version/cli' {
  declare module.exports: any;
}

declare module 'react-native-version/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-version/cli.js' {
  declare module.exports: $Exports<'react-native-version/cli'>;
}
declare module 'react-native-version/index' {
  declare module.exports: $Exports<'react-native-version'>;
}
declare module 'react-native-version/index.js' {
  declare module.exports: $Exports<'react-native-version'>;
}
declare module 'react-native-version/util.js' {
  declare module.exports: $Exports<'react-native-version/util'>;
}
