// flow-typed signature: 936562a65eace109bcf76493760e6f12
// flow-typed version: <<STUB>>/scp2_v^0.5.0/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'scp2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'scp2' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'scp2/lib/client' {
  declare module.exports: any;
}

declare module 'scp2/lib/scp' {
  declare module.exports: any;
}

// Filename aliases
declare module 'scp2/index' {
  declare module.exports: $Exports<'scp2'>;
}
declare module 'scp2/index.js' {
  declare module.exports: $Exports<'scp2'>;
}
declare module 'scp2/lib/client.js' {
  declare module.exports: $Exports<'scp2/lib/client'>;
}
declare module 'scp2/lib/scp.js' {
  declare module.exports: $Exports<'scp2/lib/scp'>;
}
