// flow-typed signature: 58bf7e9f276abd8a6930e1779587201b
// flow-typed version: <<STUB>>/ssh2-sftp-client_v^2.5.0/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ssh2-sftp-client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ssh2-sftp-client' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ssh2-sftp-client/config/ftp_config_example' {
  declare module.exports: any;
}

declare module 'ssh2-sftp-client/example/demo' {
  declare module.exports: any;
}

declare module 'ssh2-sftp-client/example/get' {
  declare module.exports: any;
}

declare module 'ssh2-sftp-client/src' {
  declare module.exports: any;
}

declare module 'ssh2-sftp-client/src/utils' {
  declare module.exports: any;
}

declare module 'ssh2-sftp-client/test/append' {
  declare module.exports: any;
}

declare module 'ssh2-sftp-client/test/checksum-tests' {
  declare module.exports: any;
}

declare module 'ssh2-sftp-client/test/fastget' {
  declare module.exports: any;
}

declare module 'ssh2-sftp-client/test/fastput' {
  declare module.exports: any;
}

declare module 'ssh2-sftp-client/test/get' {
  declare module.exports: any;
}

declare module 'ssh2-sftp-client/test/hooks/append-hooks' {
  declare module.exports: any;
}

declare module 'ssh2-sftp-client/test/hooks/checksum-hooks' {
  declare module.exports: any;
}

declare module 'ssh2-sftp-client/test/hooks/chmod-hooks' {
  declare module.exports: any;
}

declare module 'ssh2-sftp-client/test/hooks/delete-hooks' {
  declare module.exports: any;
}

declare module 'ssh2-sftp-client/test/hooks/exist-hooks' {
  declare module.exports: any;
}

declare module 'ssh2-sftp-client/test/hooks/fastGet-hooks' {
  declare module.exports: any;
}

declare module 'ssh2-sftp-client/test/hooks/fastPut-hooks' {
  declare module.exports: any;
}

declare module 'ssh2-sftp-client/test/hooks/get-hooks' {
  declare module.exports: any;
}

declare module 'ssh2-sftp-client/test/hooks/global-hooks' {
  declare module.exports: any;
}

declare module 'ssh2-sftp-client/test/hooks/list-hooks' {
  declare module.exports: any;
}

declare module 'ssh2-sftp-client/test/hooks/mkdir-hooks' {
  declare module.exports: any;
}

declare module 'ssh2-sftp-client/test/hooks/put-hooks' {
  declare module.exports: any;
}

declare module 'ssh2-sftp-client/test/hooks/rename-hooks' {
  declare module.exports: any;
}

declare module 'ssh2-sftp-client/test/hooks/rmdir-hooks' {
  declare module.exports: any;
}

declare module 'ssh2-sftp-client/test/hooks/stat-hooks' {
  declare module.exports: any;
}

declare module 'ssh2-sftp-client/test/put' {
  declare module.exports: any;
}

declare module 'ssh2-sftp-client/test/utility-methods' {
  declare module.exports: any;
}

declare module 'ssh2-sftp-client/testServer/a' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ssh2-sftp-client/config/ftp_config_example.js' {
  declare module.exports: $Exports<'ssh2-sftp-client/config/ftp_config_example'>;
}
declare module 'ssh2-sftp-client/example/demo.js' {
  declare module.exports: $Exports<'ssh2-sftp-client/example/demo'>;
}
declare module 'ssh2-sftp-client/example/get.js' {
  declare module.exports: $Exports<'ssh2-sftp-client/example/get'>;
}
declare module 'ssh2-sftp-client/src/index' {
  declare module.exports: $Exports<'ssh2-sftp-client/src'>;
}
declare module 'ssh2-sftp-client/src/index.js' {
  declare module.exports: $Exports<'ssh2-sftp-client/src'>;
}
declare module 'ssh2-sftp-client/src/utils.js' {
  declare module.exports: $Exports<'ssh2-sftp-client/src/utils'>;
}
declare module 'ssh2-sftp-client/test/append.js' {
  declare module.exports: $Exports<'ssh2-sftp-client/test/append'>;
}
declare module 'ssh2-sftp-client/test/checksum-tests.js' {
  declare module.exports: $Exports<'ssh2-sftp-client/test/checksum-tests'>;
}
declare module 'ssh2-sftp-client/test/fastget.js' {
  declare module.exports: $Exports<'ssh2-sftp-client/test/fastget'>;
}
declare module 'ssh2-sftp-client/test/fastput.js' {
  declare module.exports: $Exports<'ssh2-sftp-client/test/fastput'>;
}
declare module 'ssh2-sftp-client/test/get.js' {
  declare module.exports: $Exports<'ssh2-sftp-client/test/get'>;
}
declare module 'ssh2-sftp-client/test/hooks/append-hooks.js' {
  declare module.exports: $Exports<'ssh2-sftp-client/test/hooks/append-hooks'>;
}
declare module 'ssh2-sftp-client/test/hooks/checksum-hooks.js' {
  declare module.exports: $Exports<'ssh2-sftp-client/test/hooks/checksum-hooks'>;
}
declare module 'ssh2-sftp-client/test/hooks/chmod-hooks.js' {
  declare module.exports: $Exports<'ssh2-sftp-client/test/hooks/chmod-hooks'>;
}
declare module 'ssh2-sftp-client/test/hooks/delete-hooks.js' {
  declare module.exports: $Exports<'ssh2-sftp-client/test/hooks/delete-hooks'>;
}
declare module 'ssh2-sftp-client/test/hooks/exist-hooks.js' {
  declare module.exports: $Exports<'ssh2-sftp-client/test/hooks/exist-hooks'>;
}
declare module 'ssh2-sftp-client/test/hooks/fastGet-hooks.js' {
  declare module.exports: $Exports<'ssh2-sftp-client/test/hooks/fastGet-hooks'>;
}
declare module 'ssh2-sftp-client/test/hooks/fastPut-hooks.js' {
  declare module.exports: $Exports<'ssh2-sftp-client/test/hooks/fastPut-hooks'>;
}
declare module 'ssh2-sftp-client/test/hooks/get-hooks.js' {
  declare module.exports: $Exports<'ssh2-sftp-client/test/hooks/get-hooks'>;
}
declare module 'ssh2-sftp-client/test/hooks/global-hooks.js' {
  declare module.exports: $Exports<'ssh2-sftp-client/test/hooks/global-hooks'>;
}
declare module 'ssh2-sftp-client/test/hooks/list-hooks.js' {
  declare module.exports: $Exports<'ssh2-sftp-client/test/hooks/list-hooks'>;
}
declare module 'ssh2-sftp-client/test/hooks/mkdir-hooks.js' {
  declare module.exports: $Exports<'ssh2-sftp-client/test/hooks/mkdir-hooks'>;
}
declare module 'ssh2-sftp-client/test/hooks/put-hooks.js' {
  declare module.exports: $Exports<'ssh2-sftp-client/test/hooks/put-hooks'>;
}
declare module 'ssh2-sftp-client/test/hooks/rename-hooks.js' {
  declare module.exports: $Exports<'ssh2-sftp-client/test/hooks/rename-hooks'>;
}
declare module 'ssh2-sftp-client/test/hooks/rmdir-hooks.js' {
  declare module.exports: $Exports<'ssh2-sftp-client/test/hooks/rmdir-hooks'>;
}
declare module 'ssh2-sftp-client/test/hooks/stat-hooks.js' {
  declare module.exports: $Exports<'ssh2-sftp-client/test/hooks/stat-hooks'>;
}
declare module 'ssh2-sftp-client/test/put.js' {
  declare module.exports: $Exports<'ssh2-sftp-client/test/put'>;
}
declare module 'ssh2-sftp-client/test/utility-methods.js' {
  declare module.exports: $Exports<'ssh2-sftp-client/test/utility-methods'>;
}
declare module 'ssh2-sftp-client/testServer/a.js' {
  declare module.exports: $Exports<'ssh2-sftp-client/testServer/a'>;
}
