version: 2
publish: &publish
  working_directory: ~/my-app
  docker:
    - image: circleci/node:10.16.0
  steps:
    - checkout

    - run:
        name: Installing dependencies
        command: npm install

    - run:
        name: Bump up the version
        command: |
          git config user.name $CIRCLE_USERNAME
          npm version patch -m "Bumped version number to %s"
          git push origin master
          git push --tags

    - run:
        name: Login into Expo
        command: npx expo-cli login -u $EXPO_USERNAME -p $EXPO_PASSWORD

    - run:
        name: Publish to Expo
        command: npx expo-cli publish --non-interactive --max-workers 1 --release-channel $EXPO_RELEASE_CHANNEL

jobs:
  publish_to_expo_dev:
    environment:
      EXPO_RELEASE_CHANNEL: dev
    <<: *publish

  publish_to_expo_prod:
    environment:
      EXPO_RELEASE_CHANNEL: default
    <<: *publish

workflows:
  version: 2
  my_app:
    jobs:
      - publish_to_expo_dev:
          filters:
            branches:
              only: master
      - publish_to_expo_prod:
          filters:
            branches:
              only: master
