// flow-typed signature: a42d1a29d589a395697f1f3ddbe0619c
// flow-typed version: <<STUB>>/@expo/vector-icons_v^10.0.5/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@expo/vector-icons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@expo/vector-icons' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@expo/vector-icons/AntDesign' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/babel.config.build' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/build/AntDesign' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/build/createIconSet' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/build/createIconSetFromFontAwesome5' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/build/createIconSetFromFontello' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/build/createIconSetFromIcoMoon' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/build/createMultiStyleIconSet' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/build/Entypo' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/build/EvilIcons' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/build/Feather' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/build/FontAwesome' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/build/FontAwesome5' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/build/Foundation' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/build/iconFontSources' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/build/Icons' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/build/IconsLazy' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/build/Ionicons' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/build/MaterialCommunityIcons' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/build/MaterialIcons' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/build/Octicons' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/build/SimpleLineIcons' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/build/vendor/react-native-vector-icons/AntDesign' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/build/vendor/react-native-vector-icons/bin/add-font-assets' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/build/vendor/react-native-vector-icons/bin/generate-fontawesome5-metadata' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/build/vendor/react-native-vector-icons/bin/generate-icon' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/build/vendor/react-native-vector-icons/bin/generate-material-icons' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/build/vendor/react-native-vector-icons/Entypo' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/build/vendor/react-native-vector-icons/EvilIcons' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/build/vendor/react-native-vector-icons/Feather' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/build/vendor/react-native-vector-icons/FontAwesome' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/build/vendor/react-native-vector-icons/FontAwesome5' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/build/vendor/react-native-vector-icons/FontAwesome5Pro' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/build/vendor/react-native-vector-icons/Foundation' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/build/vendor/react-native-vector-icons' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/build/vendor/react-native-vector-icons/Ionicons' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/build/vendor/react-native-vector-icons/lib/create-icon-set-from-fontawesome5' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/build/vendor/react-native-vector-icons/lib/create-icon-set-from-fontello' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/build/vendor/react-native-vector-icons/lib/create-icon-set-from-icomoon' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/build/vendor/react-native-vector-icons/lib/create-icon-set' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/build/vendor/react-native-vector-icons/lib/create-multi-style-icon-set' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/build/vendor/react-native-vector-icons/lib/ensure-native-module-available' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/build/vendor/react-native-vector-icons/lib/generate-icon-set-from-css' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/build/vendor/react-native-vector-icons/lib/icon-button' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/build/vendor/react-native-vector-icons/lib/tab-bar-item-ios' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/build/vendor/react-native-vector-icons/lib/tab-bar-item-ios.web' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/build/vendor/react-native-vector-icons/lib/toolbar-android' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/build/vendor/react-native-vector-icons/lib/toolbar-android.web' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/build/vendor/react-native-vector-icons/MaterialCommunityIcons' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/build/vendor/react-native-vector-icons/MaterialIcons' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/build/vendor/react-native-vector-icons/Octicons' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/build/vendor/react-native-vector-icons/RNIMigration' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/build/vendor/react-native-vector-icons/SimpleLineIcons' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/build/vendor/react-native-vector-icons/Zocial' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/build/Zocial' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/createIconSet' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/createIconSetFromFontello' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/createIconSetFromIcoMoon' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/createMultiStyleIconSet' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/Entypo' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/EvilIcons' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/Feather' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/FontAwesome' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/FontAwesome5' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/Foundation' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/Ionicons' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/MaterialCommunityIcons' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/MaterialIcons' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/Octicons' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/SimpleLineIcons' {
  declare module.exports: any;
}

declare module '@expo/vector-icons/Zocial' {
  declare module.exports: any;
}

// Filename aliases
declare module '@expo/vector-icons/AntDesign.js' {
  declare module.exports: $Exports<'@expo/vector-icons/AntDesign'>;
}
declare module '@expo/vector-icons/babel.config.build.js' {
  declare module.exports: $Exports<'@expo/vector-icons/babel.config.build'>;
}
declare module '@expo/vector-icons/build/AntDesign.js' {
  declare module.exports: $Exports<'@expo/vector-icons/build/AntDesign'>;
}
declare module '@expo/vector-icons/build/createIconSet.js' {
  declare module.exports: $Exports<'@expo/vector-icons/build/createIconSet'>;
}
declare module '@expo/vector-icons/build/createIconSetFromFontAwesome5.js' {
  declare module.exports: $Exports<'@expo/vector-icons/build/createIconSetFromFontAwesome5'>;
}
declare module '@expo/vector-icons/build/createIconSetFromFontello.js' {
  declare module.exports: $Exports<'@expo/vector-icons/build/createIconSetFromFontello'>;
}
declare module '@expo/vector-icons/build/createIconSetFromIcoMoon.js' {
  declare module.exports: $Exports<'@expo/vector-icons/build/createIconSetFromIcoMoon'>;
}
declare module '@expo/vector-icons/build/createMultiStyleIconSet.js' {
  declare module.exports: $Exports<'@expo/vector-icons/build/createMultiStyleIconSet'>;
}
declare module '@expo/vector-icons/build/Entypo.js' {
  declare module.exports: $Exports<'@expo/vector-icons/build/Entypo'>;
}
declare module '@expo/vector-icons/build/EvilIcons.js' {
  declare module.exports: $Exports<'@expo/vector-icons/build/EvilIcons'>;
}
declare module '@expo/vector-icons/build/Feather.js' {
  declare module.exports: $Exports<'@expo/vector-icons/build/Feather'>;
}
declare module '@expo/vector-icons/build/FontAwesome.js' {
  declare module.exports: $Exports<'@expo/vector-icons/build/FontAwesome'>;
}
declare module '@expo/vector-icons/build/FontAwesome5.js' {
  declare module.exports: $Exports<'@expo/vector-icons/build/FontAwesome5'>;
}
declare module '@expo/vector-icons/build/Foundation.js' {
  declare module.exports: $Exports<'@expo/vector-icons/build/Foundation'>;
}
declare module '@expo/vector-icons/build/iconFontSources.js' {
  declare module.exports: $Exports<'@expo/vector-icons/build/iconFontSources'>;
}
declare module '@expo/vector-icons/build/Icons.js' {
  declare module.exports: $Exports<'@expo/vector-icons/build/Icons'>;
}
declare module '@expo/vector-icons/build/IconsLazy.js' {
  declare module.exports: $Exports<'@expo/vector-icons/build/IconsLazy'>;
}
declare module '@expo/vector-icons/build/Ionicons.js' {
  declare module.exports: $Exports<'@expo/vector-icons/build/Ionicons'>;
}
declare module '@expo/vector-icons/build/MaterialCommunityIcons.js' {
  declare module.exports: $Exports<'@expo/vector-icons/build/MaterialCommunityIcons'>;
}
declare module '@expo/vector-icons/build/MaterialIcons.js' {
  declare module.exports: $Exports<'@expo/vector-icons/build/MaterialIcons'>;
}
declare module '@expo/vector-icons/build/Octicons.js' {
  declare module.exports: $Exports<'@expo/vector-icons/build/Octicons'>;
}
declare module '@expo/vector-icons/build/SimpleLineIcons.js' {
  declare module.exports: $Exports<'@expo/vector-icons/build/SimpleLineIcons'>;
}
declare module '@expo/vector-icons/build/vendor/react-native-vector-icons/AntDesign.js' {
  declare module.exports: $Exports<'@expo/vector-icons/build/vendor/react-native-vector-icons/AntDesign'>;
}
declare module '@expo/vector-icons/build/vendor/react-native-vector-icons/bin/add-font-assets.js' {
  declare module.exports: $Exports<'@expo/vector-icons/build/vendor/react-native-vector-icons/bin/add-font-assets'>;
}
declare module '@expo/vector-icons/build/vendor/react-native-vector-icons/bin/generate-fontawesome5-metadata.js' {
  declare module.exports: $Exports<'@expo/vector-icons/build/vendor/react-native-vector-icons/bin/generate-fontawesome5-metadata'>;
}
declare module '@expo/vector-icons/build/vendor/react-native-vector-icons/bin/generate-icon.js' {
  declare module.exports: $Exports<'@expo/vector-icons/build/vendor/react-native-vector-icons/bin/generate-icon'>;
}
declare module '@expo/vector-icons/build/vendor/react-native-vector-icons/bin/generate-material-icons.js' {
  declare module.exports: $Exports<'@expo/vector-icons/build/vendor/react-native-vector-icons/bin/generate-material-icons'>;
}
declare module '@expo/vector-icons/build/vendor/react-native-vector-icons/Entypo.js' {
  declare module.exports: $Exports<'@expo/vector-icons/build/vendor/react-native-vector-icons/Entypo'>;
}
declare module '@expo/vector-icons/build/vendor/react-native-vector-icons/EvilIcons.js' {
  declare module.exports: $Exports<'@expo/vector-icons/build/vendor/react-native-vector-icons/EvilIcons'>;
}
declare module '@expo/vector-icons/build/vendor/react-native-vector-icons/Feather.js' {
  declare module.exports: $Exports<'@expo/vector-icons/build/vendor/react-native-vector-icons/Feather'>;
}
declare module '@expo/vector-icons/build/vendor/react-native-vector-icons/FontAwesome.js' {
  declare module.exports: $Exports<'@expo/vector-icons/build/vendor/react-native-vector-icons/FontAwesome'>;
}
declare module '@expo/vector-icons/build/vendor/react-native-vector-icons/FontAwesome5.js' {
  declare module.exports: $Exports<'@expo/vector-icons/build/vendor/react-native-vector-icons/FontAwesome5'>;
}
declare module '@expo/vector-icons/build/vendor/react-native-vector-icons/FontAwesome5Pro.js' {
  declare module.exports: $Exports<'@expo/vector-icons/build/vendor/react-native-vector-icons/FontAwesome5Pro'>;
}
declare module '@expo/vector-icons/build/vendor/react-native-vector-icons/Foundation.js' {
  declare module.exports: $Exports<'@expo/vector-icons/build/vendor/react-native-vector-icons/Foundation'>;
}
declare module '@expo/vector-icons/build/vendor/react-native-vector-icons/index' {
  declare module.exports: $Exports<'@expo/vector-icons/build/vendor/react-native-vector-icons'>;
}
declare module '@expo/vector-icons/build/vendor/react-native-vector-icons/index.js' {
  declare module.exports: $Exports<'@expo/vector-icons/build/vendor/react-native-vector-icons'>;
}
declare module '@expo/vector-icons/build/vendor/react-native-vector-icons/Ionicons.js' {
  declare module.exports: $Exports<'@expo/vector-icons/build/vendor/react-native-vector-icons/Ionicons'>;
}
declare module '@expo/vector-icons/build/vendor/react-native-vector-icons/lib/create-icon-set-from-fontawesome5.js' {
  declare module.exports: $Exports<'@expo/vector-icons/build/vendor/react-native-vector-icons/lib/create-icon-set-from-fontawesome5'>;
}
declare module '@expo/vector-icons/build/vendor/react-native-vector-icons/lib/create-icon-set-from-fontello.js' {
  declare module.exports: $Exports<'@expo/vector-icons/build/vendor/react-native-vector-icons/lib/create-icon-set-from-fontello'>;
}
declare module '@expo/vector-icons/build/vendor/react-native-vector-icons/lib/create-icon-set-from-icomoon.js' {
  declare module.exports: $Exports<'@expo/vector-icons/build/vendor/react-native-vector-icons/lib/create-icon-set-from-icomoon'>;
}
declare module '@expo/vector-icons/build/vendor/react-native-vector-icons/lib/create-icon-set.js' {
  declare module.exports: $Exports<'@expo/vector-icons/build/vendor/react-native-vector-icons/lib/create-icon-set'>;
}
declare module '@expo/vector-icons/build/vendor/react-native-vector-icons/lib/create-multi-style-icon-set.js' {
  declare module.exports: $Exports<'@expo/vector-icons/build/vendor/react-native-vector-icons/lib/create-multi-style-icon-set'>;
}
declare module '@expo/vector-icons/build/vendor/react-native-vector-icons/lib/ensure-native-module-available.js' {
  declare module.exports: $Exports<'@expo/vector-icons/build/vendor/react-native-vector-icons/lib/ensure-native-module-available'>;
}
declare module '@expo/vector-icons/build/vendor/react-native-vector-icons/lib/generate-icon-set-from-css.js' {
  declare module.exports: $Exports<'@expo/vector-icons/build/vendor/react-native-vector-icons/lib/generate-icon-set-from-css'>;
}
declare module '@expo/vector-icons/build/vendor/react-native-vector-icons/lib/icon-button.js' {
  declare module.exports: $Exports<'@expo/vector-icons/build/vendor/react-native-vector-icons/lib/icon-button'>;
}
declare module '@expo/vector-icons/build/vendor/react-native-vector-icons/lib/tab-bar-item-ios.js' {
  declare module.exports: $Exports<'@expo/vector-icons/build/vendor/react-native-vector-icons/lib/tab-bar-item-ios'>;
}
declare module '@expo/vector-icons/build/vendor/react-native-vector-icons/lib/tab-bar-item-ios.web.js' {
  declare module.exports: $Exports<'@expo/vector-icons/build/vendor/react-native-vector-icons/lib/tab-bar-item-ios.web'>;
}
declare module '@expo/vector-icons/build/vendor/react-native-vector-icons/lib/toolbar-android.js' {
  declare module.exports: $Exports<'@expo/vector-icons/build/vendor/react-native-vector-icons/lib/toolbar-android'>;
}
declare module '@expo/vector-icons/build/vendor/react-native-vector-icons/lib/toolbar-android.web.js' {
  declare module.exports: $Exports<'@expo/vector-icons/build/vendor/react-native-vector-icons/lib/toolbar-android.web'>;
}
declare module '@expo/vector-icons/build/vendor/react-native-vector-icons/MaterialCommunityIcons.js' {
  declare module.exports: $Exports<'@expo/vector-icons/build/vendor/react-native-vector-icons/MaterialCommunityIcons'>;
}
declare module '@expo/vector-icons/build/vendor/react-native-vector-icons/MaterialIcons.js' {
  declare module.exports: $Exports<'@expo/vector-icons/build/vendor/react-native-vector-icons/MaterialIcons'>;
}
declare module '@expo/vector-icons/build/vendor/react-native-vector-icons/Octicons.js' {
  declare module.exports: $Exports<'@expo/vector-icons/build/vendor/react-native-vector-icons/Octicons'>;
}
declare module '@expo/vector-icons/build/vendor/react-native-vector-icons/RNIMigration.js' {
  declare module.exports: $Exports<'@expo/vector-icons/build/vendor/react-native-vector-icons/RNIMigration'>;
}
declare module '@expo/vector-icons/build/vendor/react-native-vector-icons/SimpleLineIcons.js' {
  declare module.exports: $Exports<'@expo/vector-icons/build/vendor/react-native-vector-icons/SimpleLineIcons'>;
}
declare module '@expo/vector-icons/build/vendor/react-native-vector-icons/Zocial.js' {
  declare module.exports: $Exports<'@expo/vector-icons/build/vendor/react-native-vector-icons/Zocial'>;
}
declare module '@expo/vector-icons/build/Zocial.js' {
  declare module.exports: $Exports<'@expo/vector-icons/build/Zocial'>;
}
declare module '@expo/vector-icons/createIconSet.js' {
  declare module.exports: $Exports<'@expo/vector-icons/createIconSet'>;
}
declare module '@expo/vector-icons/createIconSetFromFontello.js' {
  declare module.exports: $Exports<'@expo/vector-icons/createIconSetFromFontello'>;
}
declare module '@expo/vector-icons/createIconSetFromIcoMoon.js' {
  declare module.exports: $Exports<'@expo/vector-icons/createIconSetFromIcoMoon'>;
}
declare module '@expo/vector-icons/createMultiStyleIconSet.js' {
  declare module.exports: $Exports<'@expo/vector-icons/createMultiStyleIconSet'>;
}
declare module '@expo/vector-icons/Entypo.js' {
  declare module.exports: $Exports<'@expo/vector-icons/Entypo'>;
}
declare module '@expo/vector-icons/EvilIcons.js' {
  declare module.exports: $Exports<'@expo/vector-icons/EvilIcons'>;
}
declare module '@expo/vector-icons/Feather.js' {
  declare module.exports: $Exports<'@expo/vector-icons/Feather'>;
}
declare module '@expo/vector-icons/FontAwesome.js' {
  declare module.exports: $Exports<'@expo/vector-icons/FontAwesome'>;
}
declare module '@expo/vector-icons/FontAwesome5.js' {
  declare module.exports: $Exports<'@expo/vector-icons/FontAwesome5'>;
}
declare module '@expo/vector-icons/Foundation.js' {
  declare module.exports: $Exports<'@expo/vector-icons/Foundation'>;
}
declare module '@expo/vector-icons/Ionicons.js' {
  declare module.exports: $Exports<'@expo/vector-icons/Ionicons'>;
}
declare module '@expo/vector-icons/MaterialCommunityIcons.js' {
  declare module.exports: $Exports<'@expo/vector-icons/MaterialCommunityIcons'>;
}
declare module '@expo/vector-icons/MaterialIcons.js' {
  declare module.exports: $Exports<'@expo/vector-icons/MaterialIcons'>;
}
declare module '@expo/vector-icons/Octicons.js' {
  declare module.exports: $Exports<'@expo/vector-icons/Octicons'>;
}
declare module '@expo/vector-icons/SimpleLineIcons.js' {
  declare module.exports: $Exports<'@expo/vector-icons/SimpleLineIcons'>;
}
declare module '@expo/vector-icons/Zocial.js' {
  declare module.exports: $Exports<'@expo/vector-icons/Zocial'>;
}
